#PBS -N {job_name}_{job_num}

# Walltime Limit: hh:nn:ss 
#PBS -l walltime={walltime}:00:00 

# Node Specification:
#PBS -l nodes=1:ppn=12

# Keep output
#PBS -j oe

module load qiime
cd $PBS_O_WORKDIR
cp {database_path} $TMPDIR
cp {job_num}.fna $TMPDIR
cd $TMPDIR

/usr/bin/time parallel_pick_otus_blast.py -i {job_num}.fna -r {database_fname} -O 12 -s {similarity} -o bpo.{job_num}

cp -r bpo.{job_num} $PBS_O_WORKDIR
